import { TestBed } from '@angular/core/testing';
import { NgxsModule, Store } from '@ngxs/store';
import { SubscriptionState } from './subscription.state';
import { StorageMock } from '../../mocks';
import { Storage } from '@ionic/storage';
import { SubscriptionApplyProducts, SubscriptionExpired, SubscriptionOwned, SubscriptionStateLoad } from '../actions/subscription.actions';
import { IAPProduct } from '../../../third-party/in-app-purchase-2/ngx';

fdescribe('Subscription', () => {

  let store: Store;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [NgxsModule.forRoot([SubscriptionState])],
      providers: [{provide: Storage, useClass: StorageMock}]
    });

    store = TestBed.get(Store);
  });

  it('it should have an empty state', () => {
    const state = store.selectSnapshot(SubscriptionState);
    expect(state).toEqual({
      ownedProducts: [],
      isLoading: true,
      expirationDate: null,
      userId: null,
    });
  });

  it('loads initial state', async () => {
    await store.dispatch(new SubscriptionStateLoad());
    const state = store.selectSnapshot(SubscriptionState);
    expect(state).toEqual({
      ownedProducts: [],
      isLoading: false,
      expirationDate: null,
      userId: null,
    });
  });

  it('subscribes a new product', () => {
    store.reset({
      iap: {
        ownedProducts: [],
        isLoading: false,
        expirationDate: null,
        userId: null,
      }
    });

    store.dispatch(new SubscriptionOwned({id: 'test'} as IAPProduct));

    const hasSubscription = store.selectSnapshot(SubscriptionState.hasSubscription);
    expect(hasSubscription).toBeTruthy();

    const newState = store.selectSnapshot(SubscriptionState);
    expect(newState).toEqual({
      isLoading: false,
      ownedProducts: [
        {id: 'test'} as IAPProduct,
      ],
      expirationDate: null,
      userId: null
    });
  });

  it('expires a product', () => {
    store.reset({
      iap: {
        ownedProducts: [{id: 'test'} as IAPProduct],
        isLoading: false,
        expirationDate: null,
        userId: null,
      }
    });

    store.dispatch(new SubscriptionExpired({id: 'test'} as IAPProduct));

    const hasSubscription = store.selectSnapshot(SubscriptionState.hasSubscription);
    expect(hasSubscription).toBeFalsy();

    const newState = store.selectSnapshot(SubscriptionState);
    expect(newState).toEqual({
      isLoading: false,
      ownedProducts: [],
      expirationDate: null,
      userId: null
    });
  });

  it('updates existing product state when applying the product state', () => {
    store.reset({
      iap: {
        ownedProducts: [{id: 'test'} as IAPProduct],
        isLoading: false,
        expirationDate: null,
        userId: null,
      }
    });

    store.dispatch(new SubscriptionApplyProducts([
      {id: 'test', type: 'paid subscription', owned: false} as IAPProduct
    ]));

    const hasSubscription = store.selectSnapshot(SubscriptionState.hasSubscription);
    expect(hasSubscription).toBeFalsy();

    const newState = store.selectSnapshot(SubscriptionState);
    expect(newState).toEqual({
      isLoading: false,
      ownedProducts: [],
      expirationDate: null,
      userId: null
    });
  });

  it('updates swap out paid products when applying the product state', () => {
    store.reset({
      iap: {
        ownedProducts: [{id: 'test'} as IAPProduct],
        isLoading: false,
        expirationDate: null,
        userId: null,
      }
    });

    store.dispatch(new SubscriptionApplyProducts([
      {id: 'test', type: 'paid subscription', owned: false} as IAPProduct,
      {id: 'test2', type: 'paid subscription', owned: true} as IAPProduct
    ]));

    const hasSubscription = store.selectSnapshot(SubscriptionState.hasSubscription);
    expect(hasSubscription).toBeTruthy();

    const newState = store.selectSnapshot(SubscriptionState);
    expect(newState).toEqual({
      isLoading: false,
      ownedProducts: [{id: 'test2', type: 'paid subscription', owned: true}],
      expirationDate: null,
      userId: null
    });
  });

  it('creates a new subscription even if the initial state is empty', () => {
    store.reset({
      iap: {
        ownedProducts: [],
        isLoading: false,
        expirationDate: null,
        userId: null,
      }
    });

    store.dispatch(new SubscriptionApplyProducts([
      {id: 'test', type: 'paid subscription', owned: true} as IAPProduct
    ]));

    const hasSubscription = store.selectSnapshot(SubscriptionState.hasSubscription);
    expect(hasSubscription).toBeTruthy();

    const newState = store.selectSnapshot(SubscriptionState);
    expect(newState).toEqual({
      isLoading: false,
      ownedProducts: [{id: 'test', type: 'paid subscription', owned: true}],
      expirationDate: null,
      userId: null
    });
  });

  it('works with real data', () => {
    store.reset({
      iap: {
        ownedProducts: [],
        isLoading: false,
        expirationDate: null,
        userId: null,
      }
    });

    const products = [
      {
        'id': 'com.firstphorm.apps.premium_monthly',
        'alias': 'com.firstphorm.apps.premium_monthly',
        'type': 'paid subscription',
        'group': '20499839',
        'state': 'valid',
        'title': 'My Transphormation Premium',
        'description': 'A month-to-month recurring membership.',
        'priceMicros': 5990000,
        'price': '$5.99',
        'currency': 'USD',
        'countryCode': 'US',
        'loaded': true,
        'canPurchase': true,
        'owned': false,
        'introPrice': '$0.00',
        'introPriceMicros': 0,
        'introPricePeriod': 1,
        'introPricePeriodUnit': 'Month',
        'introPricePaymentMode': 'FreeTrial',
        'ineligibleForIntroPrice': null,
        'discounts': [
          {
            'period': 1,
            'id': 'NY2020_MONTHLY',
            'price': '$0.00',
            'priceMicros': 0,
            'paymentMode': 'FreeTrial',
            'type': 'Subscription',
            'periodUnit': 'Month',
            'eligible': true
          }
        ],
        'downloading': false,
        'downloaded': false,
        'additionalData': null,
        'transaction': null,
        'billingPeriod': 1,
        'billingPeriodUnit': 'Month',
        'valid': true,
        'lastRenewalDate': '2020-02-24T21:36:16.000Z',
        'expiryDate': '2020-02-24T21:41:16.000Z',
        'isTrialPeriod': false,
        'isIntroPeriod': false,
        'renewalIntent': 'Renew',
        'purchaseDate': '2020-02-24T21:35:42.000Z',
        'isExpired': false
      } as any as IAPProduct,
      {
        'id': 'com.firstphorm.apps.premium_quarterly',
        'alias': 'com.firstphorm.apps.premium_quarterly',
        'type': 'paid subscription',
        'group': '20499839',
        'state': 'valid',
        'title': 'My Transphormation Premium',
        'description': 'A quarterly recurring membership.',
        'priceMicros': 14990000,
        'price': '$14.99',
        'currency': 'USD',
        'countryCode': 'US',
        'loaded': true,
        'canPurchase': true,
        'owned': false,
        'introPrice': '$0.00',
        'introPriceMicros': 0,
        'introPricePeriod': 1,
        'introPricePeriodUnit': 'Month',
        'introPricePaymentMode': 'FreeTrial',
        'ineligibleForIntroPrice': null,
        'discounts': [
          {
            'period': 1,
            'id': 'NY2020_QUARTERLY',
            'price': '$0.00',
            'priceMicros': 0,
            'paymentMode': 'FreeTrial',
            'type': 'Subscription',
            'periodUnit': 'Month',
            'eligible': true
          }
        ],
        'downloading': false,
        'downloaded': false,
        'additionalData': null,
        'transaction': null,
        'billingPeriod': 3,
        'billingPeriodUnit': 'Month',
        'valid': true,
        'lastRenewalDate': '2020-02-15T03:17:03.000Z',
        'expiryDate': '2020-02-15T03:32:03.000Z',
        'isTrialPeriod': false,
        'isIntroPeriod': false,
        'purchaseDate': '2020-02-15T03:16:30.000Z',
        'isExpired': true
      } as any as IAPProduct,
      {
        'id': 'com.firstphorm.apps.premium_yearly',
        'alias': 'com.firstphorm.apps.premium_yearly',
        'type': 'paid subscription',
        'group': '20499839',
        'state': 'valid',
        'title': 'My Transphormation Premium',
        'description': 'A yearly recurring membership.',
        'priceMicros': 47990000,
        'price': '$47.99',
        'currency': 'USD',
        'countryCode': 'US',
        'loaded': true,
        'canPurchase': true,
        'owned': false,
        'introPrice': '$0.00',
        'introPriceMicros': 0,
        'introPricePeriod': 1,
        'introPricePeriodUnit': 'Month',
        'introPricePaymentMode': 'FreeTrial',
        'ineligibleForIntroPrice': true,
        'discounts': [
          {
            'period': 1,
            'id': 'NY2020_YEARLY',
            'price': '$0.00',
            'priceMicros': 0,
            'paymentMode': 'FreeTrial',
            'type': 'Subscription',
            'periodUnit': 'Month',
            'eligible': true
          }
        ],
        'downloading': false,
        'downloaded': false,
        'additionalData': null,
        'transaction': null,
        'billingPeriod': 1,
        'billingPeriodUnit': 'Year',
        'valid': true,
        'lastRenewalDate': '2020-02-12T14:30:18.000Z',
        'expiryDate': '2020-02-12T15:30:18.000Z',
        'isTrialPeriod': false,
        'isIntroPeriod': false,
        'purchaseDate': '2020-02-12T14:29:33.000Z',
        'isExpired': true
      } as any as IAPProduct,
      {
        'id': 'com.firstphorm.apps',
        'alias': 'application',
        'type': 'application',
        'group': '',
        'state': 'approved',
        'title': null,
        'description': null,
        'priceMicros': null,
        'price': null,
        'currency': null,
        'countryCode': null,
        'loaded': true,
        'canPurchase': false,
        'owned': false,
        'introPrice': null,
        'introPriceMicros': null,
        'introPricePeriod': null,
        'introPriceNumberOfPeriods': null,
        'introPricePeriodUnit': null,
        'introPriceSubscriptionPeriod': null,
        'introPricePaymentMode': null,
        'ineligibleForIntroPrice': null,
        'discounts': [],
        'downloading': false,
        'downloaded': false,
        'additionalData': null,
        'transaction': {
          'type': 'ios-appstore',
          'appStoreReceipt': 'MIJ5EAYJKoZIhvcNAQcCoIJ5ATCCeP0CAQExCzAJBgUrDgMCGgUAMIJosQYJKoZIhvcNAQcBoIJoogSCaJ4xgmiaMAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgEDAgEBBAMMATQwCwIBCwIBAQQDAgEAMAsCAQ8CAQEEAwIBADALAgEQAgEBBAMCAQAwCwIBGQIBAQQDAgEDMAwCAQoCAQEEBBYCNCswDAIBDgIBAQQEAgIAjDANAgENAgEBBAUCAwH8/TANAgETAgEBBAUMAzEuMDAOAgEJAgEBBAYCBFAyNTMwGAIBBAIBAgQQ5cXSs+8tLjEC+IUjnxEumTAbAgEAAgEBBBMMEVByb2R1Y3Rpb25TYW5kYm94MBwCAQUCAQEEFG5P+Ws8Gwue1Kyrbdrzg4oV01nTMB0CAQICAQEEFQwTY29tLmZpcnN0cGhvcm0uYXBwczAeAgEMAgEBBBYWFDIwMjAtMDItMjRUMjE6MzU6NDVaMB4CARICAQEEFhYUMjAxMy0wOC0wMVQwNzowMDowMFowOQIBBwIBAQQxQwiwamPKwZBII8aGE9Bf6I6FaL3j1OjWCBDtcY8KgV/isTJqot+b3fKimYD7uOvx/DBRAgEGAgEBBEn6NSFRf6e6BAi7mHk9o+roE8SR/nOvLHO6VHwSmEpOWxjxXol+T70RNKas5H/OSmB/aQnxhIP3HyKqZUWlkQQCfUbfNEQ90souMIIBjwIBEQIBAQSCAYUxggGBMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7gaCzAbAgIGpwIBAQQSDBAxMDAwMDAwNjEyNzkyMjg0MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0wN1QwNDoxODo0MVowHwICBqoCAQEEFhYUMjAyMC0wMS0wOVQwNjoxODo1MlowHwICBqwCAQEEFhYUMjAyMC0wMS0wN1QwNToxODo0MVowLQICBqYCAQEEJAwiY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX3llYXJseTCCAY8CARECAQEEggGFMYIBgTALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe4GjwwGwICBqcCAQEEEgwQMTAwMDAwMDYxMjc5MjI3NDAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMDdUMDU6MTg6NDFaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMDlUMDY6MTg6NTJaMB8CAgasAgEBBBYWFDIwMjAtMDEtMDdUMDY6MTg6NDFaMC0CAgamAgEBBCQMImNvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV95ZWFybHkwggGPAgERAgEBBIIBhTGCAYEwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuBz3MBsCAganAgEBBBIMEDEwMDAwMDA2MTI3OTIyOTAwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTA3VDA2OjE4OjQxWjAfAgIGqgIBAQQWFhQyMDIwLTAxLTA5VDA2OjE4OjUyWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTA3VDA3OjE4OjQxWjAtAgIGpgIBAQQkDCJjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1feWVhcmx5MIIBjwIBEQIBAQSCAYUxggGBMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7ggrDAbAgIGpwIBAQQSDBAxMDAwMDAwNjMwNzkwODMwMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0wN1QwNzoxODo0MVowHwICBqoCAQEEFhYUMjAyMC0wMi0yNFQxNjoyNTo0OVowHwICBqwCAQEEFhYUMjAyMC0wMS0wN1QwODoxODo0MVowLQICBqYCAQEEJAwiY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX3llYXJseTCCAY8CARECAQEEggGFMYIBgTALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe4JcIwGwICBqcCAQEEEgwQMTAwMDAwMDYxMjc5MjI4MjAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMDdUMDg6MTg6NDFaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMDlUMDY6MTg6NTJaMB8CAgasAgEBBBYWFDIwMjAtMDEtMDdUMDk6MTg6NDFaMC0CAgamAgEBBCQMImNvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV95ZWFybHkwggGPAgERAgEBBIIBhTGCAYEwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nu/m1MBsCAganAgEBBBIMEDEwMDAwMDA2MjYwODg5MjMwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTEyVDEzOjMwOjE4WjAfAgIGqgIBAQQWFhQyMDIwLTAyLTEyVDEzOjMwOjIwWjAfAgIGrAIBAQQWFhQyMDIwLTAyLTEyVDE0OjMwOjE4WjAtAgIGpgIBAQQkDCJjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1feWVhcmx5MIIBjwIBEQIBAQSCAYUxggGBMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8RVgDAbAgIGpwIBAQQSDBAxMDAwMDAwNjI2MTE3MjU5MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0xMlQxNDozMDoxOFowHwICBqoCAQEEFhYUMjAyMC0wMi0xMlQxNDoyOTozM1owHwICBqwCAQEEFhYUMjAyMC0wMi0xMlQxNTozMDoxOFowLQICBqYCAQEEJAwiY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX3llYXJseTCCAY8CARECAQEEggGFMYIBgTALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBATAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe4GgowGwICBqcCAQEEEgwQMTAwMDAwMDYxMzc0ODU3MzAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMDdUMDQ6MTM6NDFaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTFUMDM6MjY6MTRaMB8CAgasAgEBBBYWFDIwMjAtMDEtMDdUMDQ6MTg6NDFaMC0CAgamAgEBBCQMImNvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV95ZWFybHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuCtNMBsCAganAgEBBBIMEDEwMDAwMDA2MTI3OTIyODEwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTA5VDAzOjM4OjAwWjAfAgIGqgIBAQQWFhQyMDIwLTAxLTA5VDA2OjE4OjUyWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTA5VDAzOjQzOjAwWjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe40NEwGwICBqcCAQEEEgwQMTAwMDAwMDYxMjc5MjI3NjAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMDlUMDM6NDM6MDBaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMDlUMDY6MTg6NTJaMB8CAgasAgEBBBYWFDIwMjAtMDEtMDlUMDM6NDg6MDBaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7jRHzAbAgIGpwIBAQQSDBAxMDAwMDAwNjEzNzQ4NTcxMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0wOVQwMzo0ODowMFowHwICBqoCAQEEFhYUMjAyMC0wMS0xMVQwMzoyNjoxNFowHwICBqwCAQEEFhYUMjAyMC0wMS0wOVQwMzo1MzowMFowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuNF6MBsCAganAgEBBBIMEDEwMDAwMDA2MTI3OTIyODYwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTA5VDAzOjUzOjAwWjAfAgIGqgIBAQQWFhQyMDIwLTAxLTA5VDA2OjE4OjUyWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTA5VDAzOjU4OjAwWjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe40dcwGwICBqcCAQEEEgwQMTAwMDAwMDYxMzc0ODU2NDAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMDlUMDM6NTg6MDBaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTFUMDM6MjY6MTRaMB8CAgasAgEBBBYWFDIwMjAtMDEtMDlUMDQ6MDM6MDBaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7jSHTAbAgIGpwIBAQQSDBAxMDAwMDAwNjEyNzkyMjc4MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0wOVQwNDowMzowMFowHwICBqoCAQEEFhYUMjAyMC0wMS0wOVQwNjoxODo1MlowHwICBqwCAQEEFhYUMjAyMC0wMS0wOVQwNDowODowMFowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuNJ0MBsCAganAgEBBBIMEDEwMDAwMDA2MTM3NDg1NzQwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTA5VDA0OjQyOjEzWjAfAgIGqgIBAQQWFhQyMDIwLTAxLTExVDAzOjI2OjE0WjAfAgIGrAIBAQQWFhQyMDIwLTAxLTA5VDA0OjQ3OjEzWjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe41E4wGwICBqcCAQEEEgwQMTAwMDAwMDYxMzc0ODU3ODAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMDlUMDQ6NTU6NTNaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTFUMDM6MjY6MTRaMB8CAgasAgEBBBYWFDIwMjAtMDEtMDlUMDU6MDA6NTNaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7jU/DAbAgIGpwIBAQQSDBAxMDAwMDAwNjEzNzQ4NTY4MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0wOVQwNTowOTowN1owHwICBqoCAQEEFhYUMjAyMC0wMS0xMVQwMzoyNjoxNFowHwICBqwCAQEEFhYUMjAyMC0wMS0wOVQwNToxNDowN1owLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuNWPMBsCAganAgEBBBIMEDEwMDAwMDA2MTI3OTIyODcwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTA5VDA1OjE0OjEwWjAfAgIGqgIBAQQWFhQyMDIwLTAxLTA5VDA2OjE4OjUyWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTA5VDA1OjE5OjEwWjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe41dIwGwICBqcCAQEEEgwQMTAwMDAwMDYxMzc0ODU2NTAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMDlUMDU6MjA6NTFaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTFUMDM6MjY6MTRaMB8CAgasAgEBBBYWFDIwMjAtMDEtMDlUMDU6MjU6NTFaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7jWHzAbAgIGpwIBAQQSDBAxMDAwMDAwNjEzNzQ4NTYzMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0wOVQwNTozODoyOFowHwICBqoCAQEEFhYUMjAyMC0wMS0xMVQwMzoyNjoxNFowHwICBqwCAQEEFhYUMjAyMC0wMS0wOVQwNTo0MzoyOFowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuNc4MBsCAganAgEBBBIMEDEwMDAwMDA2MTI3OTIyNzkwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTA5VDA1OjQ0OjQ3WjAfAgIGqgIBAQQWFhQyMDIwLTAxLTA5VDA2OjE4OjUyWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTA5VDA1OjQ5OjQ3WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe417YwGwICBqcCAQEEEgwQMTAwMDAwMDYxMzc0ODU2NzAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMDlUMDY6MDc6NDRaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTFUMDM6MjY6MTRaMB8CAgasAgEBBBYWFDIwMjAtMDEtMDlUMDY6MTI6NDRaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7jZnTAbAgIGpwIBAQQSDBAxMDAwMDAwNjEyNzkzNDY1MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0wOVQwNjoyMTowOVowHwICBqoCAQEEFhYUMjAyMC0wMS0wOVQwNjoyMToxMFowHwICBqwCAQEEFhYUMjAyMC0wMS0wOVQwNjoyNjowOVowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuNqvMBsCAganAgEBBBIMEDEwMDAwMDA2MTM3NTc0MjkwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTExVDA0OjQ4OjU3WjAfAgIGqgIBAQQWFhQyMDIwLTAxLTExVDA0OjQ4OjU4WjAfAgIGrAIBAQQWFhQyMDIwLTAxLTExVDA0OjUzOjU3WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe5nncwGwICBqcCAQEEEgwQMTAwMDAwMDYxMzc1Nzc5ODAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMTFUMDQ6NTM6NTdaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTFUMDQ6NTM6MDFaMB8CAgasAgEBBBYWFDIwMjAtMDEtMTFUMDQ6NTg6NTdaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7me0jAbAgIGpwIBAQQSDBAxMDAwMDAwNjEzNzU4NjYzMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0xMVQwNDo1ODo1N1owHwICBqoCAQEEFhYUMjAyMC0wMS0xMVQwNDo1ODo0M1owHwICBqwCAQEEFhYUMjAyMC0wMS0xMVQwNTowMzo1N1owLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuZ8oMBsCAganAgEBBBIMEDEwMDAwMDA2MTM3NTg4OTUwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTExVDA1OjAzOjU3WjAfAgIGqgIBAQQWFhQyMDIwLTAxLTExVDA1OjAzOjUwWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTExVDA1OjA4OjU3WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe5n1kwGwICBqcCAQEEEgwQMTAwMDAwMDYxMzc1OTE1NDAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMTFUMDU6MDg6NTdaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTFUMDU6MDc6NThaMB8CAgasAgEBBBYWFDIwMjAtMDEtMTFUMDU6MTM6NTdaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7mfizAbAgIGpwIBAQQSDBAxMDAwMDAwNjEzNzU5NDE0MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0xMVQwNToxMzo1N1owHwICBqoCAQEEFhYUMjAyMC0wMS0xMVQwNToxMjo1OVowHwICBqwCAQEEFhYUMjAyMC0wMS0xMVQwNToxODo1N1owLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuZ/SMBsCAganAgEBBBIMEDEwMDAwMDA2MTQ5NjQyMTgwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTE1VDAyOjIxOjE5WjAfAgIGqgIBAQQWFhQyMDIwLTAxLTE1VDAyOjIxOjIwWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTE1VDAyOjI2OjE5WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe6qIUwGwICBqcCAQEEEgwQMTAwMDAwMDYxNDk2NTgwMTAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMTVUMDI6MjY6MTlaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTVUMDI6MjU6MjFaMB8CAgasAgEBBBYWFDIwMjAtMDEtMTVUMDI6MzE6MTlaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8RapDAbAgIGpwIBAQQSDBAxMDAwMDAwNjI3MzAxMDUwMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0xNFQyMDo1NTowOFowHwICBqoCAQEEFhYUMjAyMC0wMi0xNFQyMDo1NTowOVowHwICBqwCAQEEFhYUMjAyMC0wMi0xNFQyMTowMDowOFowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nxV3MMBsCAganAgEBBBIMEDEwMDAwMDA2MjczMDE2NTEwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTE0VDIxOjAwOjA4WjAfAgIGqgIBAQQWFhQyMDIwLTAyLTE0VDIwOjU5OjE1WjAfAgIGrAIBAQQWFhQyMDIwLTAyLTE0VDIxOjA1OjA4WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqfFXf8wGwICBqcCAQEEEgwQMTAwMDAwMDYyNzMwMjYwNjAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDItMTRUMjE6MDU6MDhaMB8CAgaqAgEBBBYWFDIwMjAtMDItMTRUMjE6MDQ6NDRaMB8CAgasAgEBBBYWFDIwMjAtMDItMTRUMjE6MTA6MDhaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8VePDAbAgIGpwIBAQQSDBAxMDAwMDAwNjI3MzAzNDEzMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0xNFQyMToxMDowOFowHwICBqoCAQEEFhYUMjAyMC0wMi0xNFQyMTowOToxMVowHwICBqwCAQEEFhYUMjAyMC0wMi0xNFQyMToxNTowOFowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nxV5uMBsCAganAgEBBBIMEDEwMDAwMDA2MjczMDQ5NTMwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTE0VDIxOjE1OjA4WjAfAgIGqgIBAQQWFhQyMDIwLTAyLTE0VDIxOjE0OjM5WjAfAgIGrAIBAQQWFhQyMDIwLTAyLTE0VDIxOjIwOjA4WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqfFXpMwGwICBqcCAQEEEgwQMTAwMDAwMDYyNzMwNjA0NTAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDItMTRUMjE6MjA6MDhaMB8CAgaqAgEBBBYWFDIwMjAtMDItMTRUMjE6MTk6MzhaMB8CAgasAgEBBBYWFDIwMjAtMDItMTRUMjE6MjU6MDhaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8VeyTAbAgIGpwIBAQQSDBAxMDAwMDAwNjI3MzA3NzQxMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0xNFQyMTozMjoxMlowHwICBqoCAQEEFhYUMjAyMC0wMi0xNFQyMTozMjoxM1owHwICBqwCAQEEFhYUMjAyMC0wMi0xNFQyMTozNzoxMlowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nxV/cMBsCAganAgEBBBIMEDEwMDAwMDA2MjczMTA2NTYwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTE0VDIxOjQ5OjQ1WjAfAgIGqgIBAQQWFhQyMDIwLTAyLTE0VDIxOjQ5OjQ2WjAfAgIGrAIBAQQWFhQyMDIwLTAyLTE0VDIxOjU0OjQ1WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqfFYJ8wGwICBqcCAQEEEgwQMTAwMDAwMDYyNzMxMjEyMjAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDItMTRUMjE6NTc6NDhaMB8CAgaqAgEBBBYWFDIwMjAtMDItMTRUMjE6NTc6NDlaMB8CAgasAgEBBBYWFDIwMjAtMDItMTRUMjI6MDI6NDhaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8Vg7DAbAgIGpwIBAQQSDBAxMDAwMDAwNjI3MzEzODM1MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0xNFQyMjoyMDo1M1owHwICBqoCAQEEFhYUMjAyMC0wMi0xNFQyMjoyMDo1NFowHwICBqwCAQEEFhYUMjAyMC0wMi0xNFQyMjoyNTo1M1owLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nxW5rMBsCAganAgEBBBIMEDEwMDAwMDA2MzA3OTgxNDEwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTI0VDE2OjQ5OjUwWjAfAgIGqgIBAQQWFhQyMDIwLTAyLTI0VDE2OjQ5OjUxWjAfAgIGrAIBAQQWFhQyMDIwLTAyLTI0VDE2OjU0OjUwWjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqfIlf0wGwICBqcCAQEEEgwQMTAwMDAwMDYzMDc5ODk0OTAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDItMjRUMTY6NTQ6NTBaMB8CAgaqAgEBBBYWFDIwMjAtMDItMjRUMTY6NTM6NThaMB8CAgasAgEBBBYWFDIwMjAtMDItMjRUMTY6NTk6NTBaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8iWVzAbAgIGpwIBAQQSDBAxMDAwMDAwNjMwODAwOTUyMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0yNFQxNjo1OTo1MFowHwICBqoCAQEEFhYUMjAyMC0wMi0yNFQxNjo1ODo1M1owHwICBqwCAQEEFhYUMjAyMC0wMi0yNFQxNzowNDo1MFowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nyJapMBsCAganAgEBBBIMEDEwMDAwMDA2MzA4MDE1ODAwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTI0VDE3OjA0OjUwWjAfAgIGqgIBAQQWFhQyMDIwLTAyLTI0VDE3OjAzOjUyWjAfAgIGrAIBAQQWFhQyMDIwLTAyLTI0VDE3OjA5OjUwWjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqfIlxMwGwICBqcCAQEEEgwQMTAwMDAwMDYzMDg2Mjk1MTAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDItMjRUMjE6MTE6MTZaMB8CAgaqAgEBBBYWFDIwMjAtMDItMjRUMjE6MTE6MTdaMB8CAgasAgEBBBYWFDIwMjAtMDItMjRUMjE6MTY6MTZaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8ilDzAbAgIGpwIBAQQSDBAxMDAwMDAwNjMwODYzODQyMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0yNFQyMToxNjoxNlowHwICBqoCAQEEFhYUMjAyMC0wMi0yNFQyMToxNTo0MFowHwICBqwCAQEEFhYUMjAyMC0wMi0yNFQyMToyMToxNlowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nyKVEMBsCAganAgEBBBIMEDEwMDAwMDA2MzA4NjU3NTkwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTI0VDIxOjIxOjE2WjAfAgIGqgIBAQQWFhQyMDIwLTAyLTI0VDIxOjIwOjQxWjAfAgIGrAIBAQQWFhQyMDIwLTAyLTI0VDIxOjI2OjE2WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZACARECAQEEggGGMYIBgjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqfIpXYwGwICBqcCAQEEEgwQMTAwMDAwMDYzMDg2NzIwMjAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDItMjRUMjE6MjY6MTZaMB8CAgaqAgEBBBYWFDIwMjAtMDItMjRUMjE6MjU6NTBaMB8CAgasAgEBBBYWFDIwMjAtMDItMjRUMjE6MzE6MTZaMC4CAgamAgEBBCUMI2NvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9tb250aGx5MIIBkAIBEQIBAQSCAYYxggGCMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8ilrzAbAgIGpwIBAQQSDBAxMDAwMDAwNjMwODY3OTQxMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0yNFQyMTozMToxNlowHwICBqoCAQEEFhYUMjAyMC0wMi0yNFQyMTozMDoxOFowHwICBqwCAQEEFhYUMjAyMC0wMi0yNFQyMTozNjoxNlowLgICBqYCAQEEJQwjY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX21vbnRobHkwggGQAgERAgEBBIIBhjGCAYIwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nyKXWMBsCAganAgEBBBIMEDEwMDAwMDA2MzA4Njg4MDYwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTI0VDIxOjM2OjE2WjAfAgIGqgIBAQQWFhQyMDIwLTAyLTI0VDIxOjM1OjQyWjAfAgIGrAIBAQQWFhQyMDIwLTAyLTI0VDIxOjQxOjE2WjAuAgIGpgIBAQQlDCNjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fbW9udGhseTCCAZICARECAQEEggGIMYIBhDALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe6qNAwGwICBqcCAQEEEgwQMTAwMDAwMDYxNDk3NjI3NDAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMTVUMDI6NTM6NTFaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTVUMDI6NTM6NTJaMB8CAgasAgEBBBYWFDIwMjAtMDEtMTVUMDM6MDg6NTFaMDACAgamAgEBBCcMJWNvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9xdWFydGVybHkwggGSAgERAgEBBIIBiDGCAYQwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuqqgMBsCAganAgEBBBIMEDEwMDAwMDA2MTQ5ODAwNDYwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTE1VDAzOjA4OjUxWjAfAgIGqgIBAQQWFhQyMDIwLTAxLTE1VDAzOjA4OjAyWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTE1VDAzOjIzOjUxWjAwAgIGpgIBAQQnDCVjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fcXVhcnRlcmx5MIIBkgIBEQIBAQSCAYgxggGEMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7qroDAbAgIGpwIBAQQSDBAxMDAwMDAwNjE0OTg2MDUyMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0xNVQwMzoyMzo1MVowHwICBqoCAQEEFhYUMjAyMC0wMS0xNVQwMzoyMjo1MlowHwICBqwCAQEEFhYUMjAyMC0wMS0xNVQwMzozODo1MVowMAICBqYCAQEEJwwlY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX3F1YXJ0ZXJseTCCAZICARECAQEEggGIMYIBhDALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe6rNIwGwICBqcCAQEEEgwQMTAwMDAwMDYxNDk4OTc0NDAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMTVUMDM6Mzg6NTFaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTVUMDM6Mzc6NTZaMB8CAgasAgEBBBYWFDIwMjAtMDEtMTVUMDM6NTM6NTFaMDACAgamAgEBBCcMJWNvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9xdWFydGVybHkwggGSAgERAgEBBIIBiDGCAYQwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nuq3VMBsCAganAgEBBBIMEDEwMDAwMDA2MTY1MjA1MjUwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTE3VDE5OjU4OjIwWjAfAgIGqgIBAQQWFhQyMDIwLTAxLTE3VDE5OjU4OjIyWjAfAgIGrAIBAQQWFhQyMDIwLTAxLTE3VDIwOjEzOjIwWjAwAgIGpgIBAQQnDCVjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fcXVhcnRlcmx5MIIBkgIBEQIBAQSCAYgxggGEMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7v1gDAbAgIGpwIBAQQSDBAxMDAwMDAwNjE2NTIzODc4MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0xN1QyMDoxMzoyMFowHwICBqoCAQEEFhYUMjAyMC0wMS0xN1QyMDoxMjozM1owHwICBqwCAQEEFhYUMjAyMC0wMS0xN1QyMDoyODoyMFowMAICBqYCAQEEJwwlY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX3F1YXJ0ZXJseTCCAZICARECAQEEggGIMYIBhDALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe79j0wGwICBqcCAQEEEgwQMTAwMDAwMDYxNjUyNzU4MzAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMTdUMjA6Mjg6MjBaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTdUMjA6Mjc6MzZaMB8CAgasAgEBBBYWFDIwMjAtMDEtMTdUMjA6NDM6MjBaMDACAgamAgEBBCcMJWNvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9xdWFydGVybHkwggGSAgERAgEBBIIBiDGCAYQwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nu/bsMBsCAganAgEBBBIMEDEwMDAwMDA2MTY1MzAyMzEwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAxLTE3VDIwOjQzOjIwWjAfAgIGqgIBAQQWFhQyMDIwLTAxLTE3VDIwOjQyOjI2WjAfAgIGrAIBAQQWFhQyMDIwLTAxLTE3VDIwOjU4OjIwWjAwAgIGpgIBAQQnDCVjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fcXVhcnRlcmx5MIIBkgIBEQIBAQSCAYgxggGEMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p7v3mzAbAgIGpwIBAQQSDBAxMDAwMDAwNjE2NTMyMTkyMBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMS0xN1QyMDo1ODoyMFowHwICBqoCAQEEFhYUMjAyMC0wMS0xN1QyMDo1NzozNFowHwICBqwCAQEEFhYUMjAyMC0wMS0xN1QyMToxMzoyMFowMAICBqYCAQEEJwwlY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX3F1YXJ0ZXJseTCCAZICARECAQEEggGIMYIBhDALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqe7+IAwGwICBqcCAQEEEgwQMTAwMDAwMDYxNjUzNDczMDAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDEtMTdUMjE6MTM6MjBaMB8CAgaqAgEBBBYWFDIwMjAtMDEtMTdUMjE6MTI6NDhaMB8CAgasAgEBBBYWFDIwMjAtMDEtMTdUMjE6Mjg6MjBaMDACAgamAgEBBCcMJWNvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9xdWFydGVybHkwggGSAgERAgEBBIIBiDGCAYQwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nxWGzMBsCAganAgEBBBIMEDEwMDAwMDA2MjczMzczMDcwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTE1VDAyOjMyOjAzWjAfAgIGqgIBAQQWFhQyMDIwLTAyLTE1VDAyOjMyOjA0WjAfAgIGrAIBAQQWFhQyMDIwLTAyLTE1VDAyOjQ3OjAzWjAwAgIGpgIBAQQnDCVjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fcXVhcnRlcmx5MIIBkgIBEQIBAQSCAYgxggGEMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p8VtDDAbAgIGpwIBAQQSDBAxMDAwMDAwNjI3MzM4MzM5MBsCAgapAgEBBBIMEDEwMDAwMDA2MTE4MDc0MDMwHwICBqgCAQEEFhYUMjAyMC0wMi0xNVQwMjo0NzowM1owHwICBqoCAQEEFhYUMjAyMC0wMi0xNVQwMjo0NjozMlowHwICBqwCAQEEFhYUMjAyMC0wMi0xNVQwMzowMjowM1owMAICBqYCAQEEJwwlY29tLmZpcnN0cGhvcm0uYXBwcy5wcmVtaXVtX3F1YXJ0ZXJseTCCAZICARECAQEEggGIMYIBhDALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqfFbZkwGwICBqcCAQEEEgwQMTAwMDAwMDYyNzMzODkzNjAbAgIGqQIBAQQSDBAxMDAwMDAwNjExODA3NDAzMB8CAgaoAgEBBBYWFDIwMjAtMDItMTVUMDM6MDI6MDNaMB8CAgaqAgEBBBYWFDIwMjAtMDItMTVUMDM6MDE6MDZaMB8CAgasAgEBBBYWFDIwMjAtMDItMTVUMDM6MTc6MDNaMDACAgamAgEBBCcMJWNvbS5maXJzdHBob3JtLmFwcHMucHJlbWl1bV9xdWFydGVybHkwggGSAgERAgEBBIIBiDGCAYQwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nxW4KMBsCAganAgEBBBIMEDEwMDAwMDA2MjczMzk1MTcwGwICBqkCAQEEEgwQMTAwMDAwMDYxMTgwNzQwMzAfAgIGqAIBAQQWFhQyMDIwLTAyLTE1VDAzOjE3OjAzWjAfAgIGqgIBAQQWFhQyMDIwLTAyLTE1VDAzOjE2OjMwWjAfAgIGrAIBAQQWFhQyMDIwLTAyLTE1VDAzOjMyOjAzWjAwAgIGpgIBAQQnDCVjb20uZmlyc3RwaG9ybS5hcHBzLnByZW1pdW1fcXVhcnRlcmx5oIIOZTCCBXwwggRkoAMCAQICCA7rV4fnngmNMA0GCSqGSIb3DQEBBQUAMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE1MTExMzAyMTUwOVoXDTIzMDIwNzIxNDg0N1owgYkxNzA1BgNVBAMMLk1hYyBBcHAgU3RvcmUgYW5kIGlUdW5lcyBTdG9yZSBSZWNlaXB0IFNpZ25pbmcxLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKXPgf0looFb1oftI9ozHI7iI8ClxCbLPcaf7EoNVYb/pALXl8o5VG19f7JUGJ3ELFJxjmR7gs6JuknWCOW0iHHPP1tGLsbEHbgDqViiBD4heNXbt9COEo2DTFsqaDeTwvK9HsTSoQxKWFKrEuPt3R+YFZA1LcLMEsqNSIH3WHhUa+iMMTYfSgYMR1TzN5C4spKJfV+khUrhwJzguqS7gpdj9CuTwf0+b8rB9Typj1IawCUKdg7e/pn+/8Jr9VterHNRSQhWicxDkMyOgQLQoJe2XLGhaWmHkBBoJiY5uB0Qc7AKXcVz0N92O9gt2Yge4+wHz+KO0NP6JlWB7+IDSSMCAwEAAaOCAdcwggHTMD8GCCsGAQUFBwEBBDMwMTAvBggrBgEFBQcwAYYjaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy13d2RyMDQwHQYDVR0OBBYEFJGknPzEdrefoIr0TfWPNl3tKwSFMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUiCcXCam2GGCL7Ou69kdZxVJUo7cwggEeBgNVHSAEggEVMIIBETCCAQ0GCiqGSIb3Y2QFBgEwgf4wgcMGCCsGAQUFBwICMIG2DIGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wNgYIKwYBBQUHAgEWKmh0dHA6Ly93d3cuYXBwbGUuY29tL2NlcnRpZmljYXRlYXV0aG9yaXR5LzAOBgNVHQ8BAf8EBAMCB4AwEAYKKoZIhvdjZAYLAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAA2mG9MuPeNbKwduQpZs0+iMQzCCX+Bc0Y2+vQ+9GvwlktuMhcOAWd/j4tcuBRSsDdu2uP78NS58y60Xa45/H+R3ubFnlbQTXqYZhnb4WiCV52OMD3P86O3GH66Z+GVIXKDgKDrAEDctuaAEOR9zucgF/fLefxoqKm4rAfygIFzZ630npjP49ZjgvkTbsUxn/G4KT8niBqjSl/OnjmtRolqEdWXRFgRi48Ff9Qipz2jZkgDJwYyz+I0AZLpYYMB8r491ymm5WyrWHWhumEL1TKc3GZvMOxx6GUPzo22/SGAGDDaSK+zeGLUR2i0j0I78oGmcFxuegHs5R0UwYS/HE6gwggQiMIIDCqADAgECAggB3rzEOW2gEDANBgkqhkiG9w0BAQUFADBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMTMwMjA3MjE0ODQ3WhcNMjMwMjA3MjE0ODQ3WjCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMo4VKbLVqrIJDlI6Yzu7F+4fyaRvDRTes58Y4Bhd2RepQcjtjn+UC0VVlhwLX7EbsFKhT4v8N6EGqFXya97GP9q+hUSSRUIGayq2yoy7ZZjaFIVPYyK7L9rGJXgA6wBfZcFZ84OhZU3au0Jtq5nzVFkn8Zc0bxXbmc1gHY2pIeBbjiP2CsVTnsl2Fq/ToPBjdKT1RpxtWCcnTNOVfkSWAyGuBYNweV3RY1QSLorLeSUheHoxJ3GaKWwo/xnfnC6AllLd0KRObn1zeFM78A7SIym5SFd/Wpqu6cWNWDS5q3zRinJ6MOL6XnAamFnFbLw/eVovGJfbs+Z3e8bY/6SZasCAwEAAaOBpjCBozAdBgNVHQ4EFgQUiCcXCam2GGCL7Ou69kdZxVJUo7cwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAuBgNVHR8EJzAlMCOgIaAfhh1odHRwOi8vY3JsLmFwcGxlLmNvbS9yb290LmNybDAOBgNVHQ8BAf8EBAMCAYYwEAYKKoZIhvdjZAYCAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAE/P71m+LPWybC+P7hOHMugFNahui33JaQy52Re8dyzUZ+L9mm06WVzfgwG9sq4qYXKxr83DRTCPo4MNzh1HtPGTiqN0m6TDmHKHOz6vRQuSVLkyu5AYU2sKThC22R1QbCGAColOV4xrWzw9pv3e9w0jHQtKJoc/upGSTKQZEhltV/V6WId7aIrkhoxK6+JJFKql3VUAqa67SzCu4aCxvCmA5gl35b40ogHKf9ziCuY7uLvsumKV8wVjQYLNDzsdTJWk26v5yZXpT+RN5yaZgem8+bQp0gF6ZuEujPYhisX4eOGBrr/TkJ2prfOv/TgalmcwHFGlXOxxioK0bA8MFR8wggS7MIIDo6ADAgECAgECMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0wNjA0MjUyMTQwMzZaFw0zNTAyMDkyMTQwMzZaMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOSRqQkfkdseR1DrBe1eeYQt6zaiV0xV7IsZid75S2z1B6siMALoGD74UAnTf0GomPnRymacJGsR0KO75Bsqwx+VnnoMpEeLW9QWNzPLxA9NzhRp0ckZcvVdDtV/X5vyJQO6VY9NXQ3xZDUjFUsVWR2zlPf2nJ7PULrBWFBnjwi0IPfLrCwgb3C2PwEwjLdDzw+dPfMrSSgayP7OtbkO2V4c1ss9tTqt9A8OAJILsSEWLnTVPA3bYharo3GSR1NVwa8vQbP4++NwzeajTEV+H0xrUJZBicR0YgsQg0GHM4qBsTBY7FoEMoxos48d3mVz/2deZbxJ2HafMxRloXeUyS0CAwEAAaOCAXowggF2MA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjCCAREGA1UdIASCAQgwggEEMIIBAAYJKoZIhvdjZAUBMIHyMCoGCCsGAQUFBwIBFh5odHRwczovL3d3dy5hcHBsZS5jb20vYXBwbGVjYS8wgcMGCCsGAQUFBwICMIG2GoGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wDQYJKoZIhvcNAQEFBQADggEBAFw2mUwteLftjJvc83eb8nbSdzBPwR+Fg4UbmT1HN/Kpm0COLNSxkBLYvvRzm+7SZA/LeU802KI++Xj/a8gH7H05g4tTINM4xLG/mk8Ka/8r/FmnBQl8F0BWER5007eLIztHo9VvJOLr0bdw3w9F4SfK8W147ee1Fxeo3H4iNcol1dkP1mvUoiQjEfehrI9zgWDGG1sJL5Ky+ERI8GA4nhX1PSZnIIozavcNgs/e66Mv+VNqW2TAYzN39zoHLFbr2g8hDtq6cxlPtdk2f8GHVdmnmbkyQvvY1XGefqFStxu9k0IkEirHDx22TZxeY8hLgBdQqorV2uT80AkHN7B1dSExggHLMIIBxwIBATCBozCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eQIIDutXh+eeCY0wCQYFKw4DAhoFADANBgkqhkiG9w0BAQEFAASCAQAsl0SYPu88qco/lguvaU3Kh8aOcMxy53YC0ND02KZHzGoZI9yZ/1zZYYZJb7shBSx8DGrhyXXPkjyYYbDIu4L+ALkST9Ytkj8CPTrTASGnyAIZD/J+aRCHTtyoFYAYlqNTrHDAHjGXZ4+Ww2hCjoBticzBypl4MuQfPqq1gNJqAhJctFDGGWY60ABRUsRyTYDgHr2r4sQpWHXLELs7ijqs3TQetVD/1/oZHRDykCFYo1mwN6nQMlioEuKJx1yR2UnCgCRovJU2Fdphe8vnxjWLm4+/Ufbp1fBveoGiCjqknjp6+/GtE6LyjzfM2e9pFUFeP/3aURKJIpLL9pOq09ih'
        },
        'version': '2.2.0',
        'valid': true
      } as any as IAPProduct
    ];
    store.dispatch(new SubscriptionApplyProducts(products));

    const hasSubscription = store.selectSnapshot(SubscriptionState.hasSubscription);
    expect(hasSubscription).toBeFalsy();

    const newState = store.selectSnapshot(SubscriptionState);
    expect(newState).toEqual({
      isLoading: false,
      ownedProducts: [],
      expirationDate: null,
      userId: null
    });
  });
});
